### ISSUE TITLE
Decryption works first time but throws "InvalidKeyIdException - No such prekeyrecord!" if recalled

### ISSUE THREAD

**Issue by sabin26** [MixinNetwork/libsignal_protocol_dart#15]
```
import 'dart:typed_data';

import 'package:libsignal_protocol_dart/libsignal_protocol_dart.dart';

class Session {
  final SignalProtocolStore self;
  PreKeyBundle otherKeyBundle;
  SignalProtocolAddress otherAddress;
  SessionCipher cipher;
  Session(this.self, this.otherKeyBundle, this.otherAddress);

  void build() {
    var builder = SessionBuilder(self, self, self, self, otherAddress);
    builder.processPreKeyBundle(otherKeyBundle);
    cipher = SessionCipher(self, self, self, self, otherAddress);
  }

  PreKeySignalMessage encrypt(Uint8List message) {
    var ciphertext = cipher.encrypt(message);
    var rawCiphertext = ciphertext.serialize();
    var encrypted = PreKeySignalMessage(rawCiphertext);
    return encrypted;
  }

  Uint8List decrypt(PreKeySignalMessage ciphertext) {
    var decrypted = cipher.decrypt(ciphertext);
    return decrypted;
  }
}
```
Encryption works every time I call encrypt() function but decrypt() function works only the first time. The second or third time I call this function it throws: "**InvalidKeyIdException - No such prekeyrecord! - 2**"

![Error](https://user-images.githubusercontent.com/61322712/97415703-ab1d9f00-192d-11eb-99bd-5d13726e9f1a.png)

**Comment by xni06** [comment]
- Alice sends msg to Bob using the preKey from his bundle - `otherKeyBundle` in your example
- Bob decrypts msg and deletes the preKey from his local store
- Alice sends another msg to Bob using the same preKey that she used the first time - however, Bob has deleted it on his side hence the `InvalidKeyIdException`

**Solution**
- Prevent Alice from sending subsequent messages to Bob until Bob replies thus establishing a secure communication channel
- Request another preKeyBundle from Bob which has a different preKey

Note that once a secure channel has been established, you'll then need to use `decryptFromSignal`, not `decrypt`

I hope this shines enough light on the cause of this exception to get you going again. I know in my case, it took a long time to get things working from a client side but once the process is understood, it works nicely,

**Comment by sabin26** [comment]
The secure channel is established by calling `sessionBuilder()` and processing it with the Bob's `preKeyBundle` before any message is sent or received. After establishing the session, Alice can use `encrypt()` to send SignalMessage and `decryptFromSignal()` to receive Bob's message. Is this the correct way of implementation ?

**Comment by xni06** [comment]
The channel is not secure until Bob has replied to Alice. Once established, the ratcheting mechanism takes place to keep keys in sync.

Take a look at [test/session_builder_test.dart](https://github.com/MixinNetwork/libsignal_protocol_dart/blob/master/test/session_builder_test.dart)

**Comment by sabin26** [comment]
Can you please provide a sample working code or maybe edit my initial code. I am a beginner in this and the documentation around implementing signal protocol is very restricted. I even checked the original java github page but did not find anything useful. Any help is highly appreciated.

**Comment by xni06** [comment]
> Can you please provide a sample working code

Take a look at [test/session_builder_test.dart](https://github.com/MixinNetwork/libsignal_protocol_dart/blob/master/test/session_builder_test.dart)

**Comment by crossle** [comment]
> Can you please provide a sample working code or maybe edit my initial code. I am a beginner in this and the documentation around implementing signal protocol is very restricted. I even checked the original java github page but did not find anything useful. Any help is highly appreciated.

Mixin Messenger also use Signal Protocol, take a look 
https://github.com/MixinNetwork/android-app/blob/master/app/src/main/java/one/mixin/android/crypto/SignalProtocol.kt

**Comment by sabin26** [comment]
I somehow managed to make my code work. Thank you for your help @xni06 and @crossle
