### ISSUE TITLE
GPL-License and its implications

### ISSUE THREAD

**Issue by robojones** [MixinNetwork/libsignal_protocol_dart#16]
I want to use this library in an open-source application. However, I don't want to release my work under GPL-3 because I don't like the license.

Does an application using your library constitute a derivative work and can it be released under a different open-source license?
Namely, I would prefer the MIT or Apache-2 license.

**Comment by xni06** [comment]
Just out of interest, what exactly is it that you don't like regarding the existing licence?

**Comment by robojones** [comment]
I don't like GPL because there is lots of **uncertainty** in the open-source community about the legal implications of using it.
When googling it I was unable to get a clear answer on what limitations apply to my software when I am using a GPL-3 library.

In contrast to this, **most people know** that MIT or Apache-2 licensed software can be used without limitations. Products which are using MIT or Apache licensed libraries and components can be released under any license the author likes.

**Comment by crossle** [comment]
Good suggestion, use GPLv3 just like https://github.com/signalapp/libsignal-protocol-java.
Any other suggestions?

**Comment by steebchen** [comment]
I agree that a more permissive license such as MIT would be a greater fit for this library and would attract more users and contributors to the project.

**Comment by robojones** [comment]
@steebchen thanks for the suggestion. Here is a PR for this.

**Comment by crossle** [comment]
Thanks. Merged

**Comment by cedricfung** [comment]
https://github.com/MixinNetwork/libsignal_protocol_dart/issues/19
