### ISSUE TITLE
Does this uses Double ratchet by default or we have to make that ourselves?

### ISSUE THREAD

**Issue by ceojazzy** [MixinNetwork/libsignal_protocol_dart#18]

**Comment by xni06** [comment]
It uses double-ratchet by default

https://github.com/MixinNetwork/libsignal_protocol_dart/tree/master/lib/src/ratchet

**Comment by ceojazzy** [comment]
thankyou for the answer.
can you also tell if this uses Curve25519?
thanks

**Comment by xni06** [comment]
It uses [ed25519](https://github.com/MixinNetwork/libsignal_protocol_dart/pull/5)

**Comment by ceojazzy** [comment]
So the keys are generated randomly? i have seen some articles where they says that ed25519 is hackable rather than the x25519. this will be my last silly of questions for sure.

**Comment by ceojazzy** [comment]
?

**Comment by crossle** [comment]
The key is curve25519. It's random.

**Comment by ceojazzy** [comment]
So random is hackable? @crossle

**Comment by Tougee** [comment]
Random does not mean hackable. The things you care about  are not actually associated with this project, you can check out the signal protocol information [here](https://signal.org/docs/).

**Comment by Ahmadre** [comment]
> So random is hackable? @crossle 

Nope! This lib uses X25519:

See:
lib/src/ecc/Curve.dart

It's supereasy with the dart packages x25519 and cryptography. Just search on pub.dev and you can make your own algorithms out of them.
