### ISSUE TITLE
No legalities involved as this is under MIT license and the Signal protocol is GPLv3?

### ISSUE THREAD

**Issue by vishal-android-freak** [MixinNetwork/libsignal_protocol_dart#19]
We are planning to write a Flutter app which is closed source. I came across this implementation of the Signal protocol and was wondering if this is okay considering no infringement of any license as this is published under MIT. You have mentioned the algorithms as references but is it okay to reproduce the same and put it under MIT?

**Comment by Tougee** [comment]
IMO, the GPL is a software license, which means it only affects signal protocol libraries, not the protocol itself. So I think you can use this library in a closed source project. 
But if your project is not open source, how can you prove to your users that you are using this protocol library?

**Comment by vishal-android-freak** [comment]
Excellent point. We are very confused on similar points. It will be a make
or break decision for us when we go ahead with it. I was making sure we
don't end up in trouble over the course of time.

**Comment by cedricfung** [comment]
So discussions suggest a translation of source code from a language to another, should be treated as a modification. Thus should remain GPL. 

https://stackoverflow.com/questions/1723606/should-translations-of-some-gpl-code-to-other-languages-be-licensed-as-gpl

https://www.reddit.com/r/programming/comments/94446/ask_proggit_porting_a_gpl_project_to_a_new/

Not a lawyer.

**Comment by Ahmadre** [comment]
> So discussions suggest a translation of source code from a language to another, should be treated as a modification. Thus should remain GPL. 
> 
> 
> 
> https://stackoverflow.com/questions/1723606/should-translations-of-some-gpl-code-to-other-languages-be-licensed-as-gpl
> 
> 
> 
> https://www.reddit.com/r/programming/comments/94446/ask_proggit_porting_a_gpl_project_to_a_new/
> 
> 
> 
> Not a lawyer.

Exactly! This library is open source and you guys can use it! I started earlier a version of Signal in flutter but @crossle did a much greater job here 💪🏼 so it's still GPLv3 like Signal native implementations.
