### ISSUE TITLE
How to share public keys

### ISSUE THREAD

**Issue by alsiPanda** [MixinNetwork/libsignal_protocol_dart#21]
I am trying to use libsignal in my flutter web app, and currently facing this problem. I need to save the public keys and share them with a different user. My current approach is to serialize the key, convert to string, put it in a map<string, string>, jsonEncode the string and finally save it on server. Problem is when retrieving the key, i get this error `Error: Expected a value of type 'ECPublicKey', but got one of type 'NativeUint8List'`. The code I am using when retrieving is as follows:

    var bundle = json.decode(otherUser.publicKey);
    ECPublicKey preKeyPublic = Uint8List.fromList(jsonDecode(bundle['preKey']).cast<int>()) as ECPublicKey;
    ECPublicKey signedPreKeyPublic = Uint8List.fromList(jsonDecode(bundle['signedPreKey']).cast<int>()) as ECPublicKey;
    Uint8List signedPreKeySignature = Uint8List.fromList(jsonDecode(bundle['signature']).cast<int>());
    IdentityKey identityKey = IdentityKey.fromBytes(Uint8List.fromList(jsonDecode(bundle['identityKeyPair']).cast<int>()), 0) ;

    var recieverBundle = PreKeyBundle(registrationId, 0, 0, preKeyPublic, 0, signedPreKeyPublic, signedPreKeySignature, identityKey);

recieverBundle goes into the sessionBuilder. Due to the errors, I am now saving the entire keypair for prekey and signedprekey, since they have the fromBuffer function and making it available publicly. But I dont know if that would be a security issue, since common sense dictates private key should never be shared.

 I am new to encryption in general, and a beginner in flutter web. I cant seem to figure out how else to save the public keys and retrieve them. Any help would be appreciated.

**Comment by xni06** [comment]
As a quick pointer, you need to make use of a `DjbECPublicKey` to create a `ECPublicKey`:

```
final key = DjbECPublicKey(yourUint8List);

final ecPublicKey = Curve.decodePoint(key.serialize(), 1);
```

**Comment by alsiPanda** [comment]
Thanks @xni06 , that worked like a charm. 
I have one more query/doubt. Can I use `session.encrypt` to encrypt images and videos as well, since it accepts uint8list as input. If so can the decrypted bytes be directly used to reconstruct the media. Does Signal app do it the same/similar way ?

**Comment by xni06** [comment]
> Thanks @xni06 , that worked like a charm.
> I have one more query/doubt. Can I use `session.encrypt` to encrypt images and videos as well, since it accepts uint8list as input. If so can the decrypted bytes be directly used to reconstruct the media. Does Signal app do it the same/similar way ?

Sorry, I don't know.

**Comment by Tougee** [comment]
Hi @alsiPanda,
Signal does not use `session.encrypt` for encrypting large media data, they just use another random bytes for media encryption, and use signal keys to encrypt the media key and media digest.
If you want to know more about it, you can search `AES/CBC + HMAC` or `AES/GCM` for more information.

**Comment by alsiPanda** [comment]
Thanks @Tougee, I recently read something similar in Whatsapp whitepaper.

**Comment by ghost** [comment]
> As a quick pointer, you need to make use of a `DjbECPublicKey` to create a `ECPublicKey`:
> 
> ```
> final key = DjbECPublicKey(yourUint8List);
> 
> final ecPublicKey = Curve.decodePoint(key.serialize(), 1);
> ```

Would this work for ECPrivateKey as well? I just ask as I have to store it in a local file. Is the offset for `Curve.decodePoint` always `1`?

Thanks a lot!

**Comment by crossle** [comment]
Because the first is the type, Curve.djbType, so when your wanna decode to curve alway start from 1.
