### ISSUE TITLE
Example code does not work

### ISSUE THREAD

**Issue by xni06** [MixinNetwork/libsignal_protocol_dart#24]
While not an issue for me personally, the [example](https://github.com/MixinNetwork/libsignal_protocol_dart/blob/master/example/main.dart) does not work:

```
MacBook:example $ dart main.dart 
Unhandled exception:
Assertion failed: Instance of 'InvalidKeyException'
#0      SessionState.getSenderRatchetKey (package:libsignal_protocol_dart/src/state/SessionState.dart:104:7)
#1      SessionCipher.encrypt (package:libsignal_protocol_dart/src/SessionCipher.dart:59:40)
#2      install (file:///Users/rhisiart/git/libsignal_protocol_dart/example/main.dart:38:34)
#3      main (file:///Users/rhisiart/git/libsignal_protocol_dart/example/main.dart:6:3)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by crossle** [comment]
The example not a complete process

**Comment by xni06** [comment]
Perhaps the code should be documented to help others know what they should expect to see when they run it to avoid confusion.

**Comment by woinbo** [comment]
Hey mixinNetwork, Please update the example as it is not the correct way to implement this protocol and even the readme file is not documented properly it is becoming really hard to use this protocol.

**Comment by crossle** [comment]
Example run ok now.

**Comment by woinbo** [comment]
Thank you @crossle , it did worked now
