### ISSUE TITLE
not an issue but a suggestion

### ISSUE THREAD

**Issue by woinbo** [MixinNetwork/libsignal_protocol_dart#25]
Can you guys make a YouTube video on how to implement this package into a real life app like very simple chatting app just having chatting and end to end encryption using signal. This will be really helpful to the community. Thank you!!

**Comment by crossle** [comment]
We are working on using this library for our desktop app. It's will open source.

**Comment by woinbo** [comment]
any update on this, when this project is going to be open source?? @crossle

**Comment by crossle** [comment]
Working on it.

**Comment by Ahmadre** [comment]
> any update on this, when this project is going to be open source?? @crossle 

I don't understand your concerns...libsignal is based on Signal Protocol and have therefore the same Licence like Signal. So it is already Open-Source

**Comment by crossle** [comment]
> > any update on this, when this project is going to be open source?? @crossle
> 
> I don't understand your concerns...libsignal is based on Signal Protocol and have therefore the same Licence like Signal. So it is already Open-Source

We are working to develop an app use this library.

**Comment by woinbo** [comment]
> > any update on this, when this project is going to be open source?? @crossle
> 
> I don't understand your concerns...libsignal is based on Signal Protocol and have therefore the same Licence like Signal. So it is already Open-Source

Actually, I am not talking about this libsignal_protocol_dart, I am referring to the project on which these guys from the mixin network are working on.
