### ISSUE TITLE
How to handle emoji while encryption/decryption?

### ISSUE THREAD

**Issue by sky-flutter** [MixinNetwork/libsignal_protocol_dart#26]
Hey, I try encryption and decryption with text, and it works perfectly. But when I add emoji in the text the emoji could not get decrypt in Unicode or in another format. So can you please guide me on how can handle emoji in the text?

**Comment by crossle** [comment]
Example https://github.com/MixinNetwork/libsignal_protocol_dart/commit/65c4a45a514aa4130ed8982351b6fa7492e759bf

**Comment by sky-flutter** [comment]
Okay, It works for me. Thanks.
