### ISSUE TITLE
optional one-time prekey

### ISSUE THREAD

**Issue by doc-dev** [MixinNetwork/libsignal_protocol_dart#27]
The documentation is not clear enough. The official Signal documentation of X3DH (https://signal.org/docs/specifications/x3dh/) says that the one-time prekey are optional. However it seems that in the current implementation there must be necessarily a pre-key bundle.

I was wondering how to manage the various keys at a lower level, so that I can create a JSON that can be sent to my backend

**Comment by crossle** [comment]
The pre-key id and pub key can null on PreKeyBundle.

Use persistence method, store in file or like objectbox-dart

**Comment by carzacc** [comment]
> The pre-key id and pub key can null on PreKeyBundle.
> 
> Use persistence method, store in file or like objectbox-dart

It doesn't look like that's the case to me: the SPK and its signature (but not its ID) are nullable, but the OPK and its ID (which are supposed to be nullable) are not.

It's quite clear:
https://github.com/MixinNetwork/libsignal_protocol_dart/blob/master/lib/src/state/pre_key_bundle.dart

**Comment by crossle** [comment]
> > The pre-key id and pub key can null on PreKeyBundle.
> > Use persistence method, store in file or like objectbox-dart
> 
> It doesn't look like that's the case to me: the SPK and its signature (but not its ID) are nullable, but the OPK and its ID (which are supposed to be nullable) are not.
> 
> It's quite clear: https://github.com/MixinNetwork/libsignal_protocol_dart/blob/master/lib/src/state/pre_key_bundle.dart

https://github.com/MixinNetwork/libsignal_protocol_dart/blob/8387df165ecfadad9eeab2fd187d926bfb47282a/lib/src/session_builder.dart#L125  here the OPK proces if empty

**Comment by carzacc** [comment]
> > > The pre-key id and pub key can null on PreKeyBundle.
> > > Use persistence method, store in file or like objectbox-dart
> > 
> > 
> > It doesn't look like that's the case to me: the SPK and its signature (but not its ID) are nullable, but the OPK and its ID (which are supposed to be nullable) are not.
> > It's quite clear: https://github.com/MixinNetwork/libsignal_protocol_dart/blob/master/lib/src/state/pre_key_bundle.dart
> 
> https://github.com/MixinNetwork/libsignal_protocol_dart/blob/8387df165ecfadad9eeab2fd187d926bfb47282a/lib/src/session_builder.dart#L125
> here the OPK proces if empty

I don't quite understand: how am I supposed to create a PreKeyBundle without an OPK if that constructor parameter is non-nullable?

**Comment by crossle** [comment]
> > > > The pre-key id and pub key can null on PreKeyBundle.
> > > > Use persistence method, store in file or like objectbox-dart
> > > 
> > > 
> > > It doesn't look like that's the case to me: the SPK and its signature (but not its ID) are nullable, but the OPK and its ID (which are supposed to be nullable) are not.
> > > It's quite clear: https://github.com/MixinNetwork/libsignal_protocol_dart/blob/master/lib/src/state/pre_key_bundle.dart
> > 
> > 
> > https://github.com/MixinNetwork/libsignal_protocol_dart/blob/8387df165ecfadad9eeab2fd187d926bfb47282a/lib/src/session_builder.dart#L125
> > 
> > here the OPK proces if empty
> 
> I don't quite understand: how am I supposed to create a PreKeyBundle without an OPK if that constructor parameter is non-nullable?

You can leave an empty data.

**Comment by carzacc** [comment]
> > > > > The pre-key id and pub key can null on PreKeyBundle.
> > > > > Use persistence method, store in file or like objectbox-dart
> > > > 
> > > > 
> > > > It doesn't look like that's the case to me: the SPK and its signature (but not its ID) are nullable, but the OPK and its ID (which are supposed to be nullable) are not.
> > > > It's quite clear: https://github.com/MixinNetwork/libsignal_protocol_dart/blob/master/lib/src/state/pre_key_bundle.dart
> > > 
> > > 
> > > https://github.com/MixinNetwork/libsignal_protocol_dart/blob/8387df165ecfadad9eeab2fd187d926bfb47282a/lib/src/session_builder.dart#L125
> > > 
> > > here the OPK proces if empty
> > 
> > 
> > I don't quite understand: how am I supposed to create a PreKeyBundle without an OPK if that constructor parameter is non-nullable?
> 
> You can leave an empty data.

I can't use `null` because `_preKeyPublic` is non nullable, should I use a `DjbECPublicKey` created with a zero-length `Uint8List`?

**Comment by crossle** [comment]
> DjbECPublicKey

Yes

**Comment by carzacc** [comment]
> > DjbECPublicKey
> 
> Yes

That doesn't work, if I pass a zero-length Uint8List to create a `DjbECPublicKey` when I call `processPreKeyBundle` it ends up being passed straight to the x25519 library which obviously doesn't accept it as valid.

**Comment by carzacc** [comment]
Since it doesn't look like we're managing to understand each other, could you please tell me how one could edit https://github.com/MixinNetwork/libsignal_protocol_dart/blob/master/example/main.dart to make it work without an OPK?

**Comment by Tougee** [comment]
Done with https://github.com/MixinNetwork/libsignal_protocol_dart/pull/60
