### ISSUE TITLE
Unexpected behaviour from generatePreKeys

### ISSUE THREAD

**Issue by rlch** [MixinNetwork/libsignal_protocol_dart#29]
Hey!

```dart
  static List<PreKeyRecord> generatePreKeys(int start, int count) {
    var results = <PreKeyRecord>[];
    start--;
    for (var i = 0; i < count; i++) {
      results.add(PreKeyRecord(
          ((start + i) % (Medium.MAX_VALUE - 1)) + 1, Curve.generateKeyPair()));
    }
    return results;
  }
```
Here, with `generatePreKeys(0, 100)` we would expect an output of `0...99` - according to the Java docs noting `start` as inclusive. However, due to the difference in modulo operators between Dart and Java (Euclidean vs Truncated), the first iteration of the function will give Medium.MAX_VALUE - 1 as the first ID. 

A simple fix for this is replacing `%` with `.remainder()`

**Comment by xni06** [comment]
Imagine that this library has already been consumed by a project and has generated keys - updating the library would mean that new preKeys  would be generated differently. Would this be an issue?

**Comment by rlch** [comment]
I don't think it'd be an issue. All it will do is cause a single ID gap, for instance pre update the current pre-key ids are: `101,102`, and post-update generation will give: `101,102,104,105,....`

Fairly certain the ID's themselves have no algorithmic importance beyond uniquely identifying the OTK, so I personally think it's fine.
