### ISSUE TITLE
documentation about how's the API designed and what every feild mean in proto?

### ISSUE THREAD

**Issue by lucasjinreal** [MixinNetwork/libsignal_protocol_dart#32]
documentation about how's the API designed and what every feild mean in proto?

**Comment by rlch** [comment]
+1, although in the mean time the Java API is pretty extensive! Have a look at that :)

**Comment by crossle** [comment]
> documentation about how's the API designed and what every feild mean in proto?

The API from signal Java library

**Comment by lucasjinreal** [comment]
@crossle Do u have a linnk of it?

**Comment by rlch** [comment]
> @crossle Do u have a linnk of it?

https://github.com/signalapp/libsignal-service-java

**Comment by xni06** [comment]
Perhaps it would be a good idea to mention in the README that this library is a Dart conversion of https://github.com/signalapp/libsignal-service-java - any complaints regarding documentation/implementation, etc. can then be directed to the source rather than this library.
