### ISSUE TITLE
Key serialization issue: InvalidKeyException - Invalid signature on device key! 

### ISSUE THREAD

**Issue by rlch** [MixinNetwork/libsignal_protocol_dart#33]
Hey,

What's the best way of serializing each key consistently, so that they are properly stored in a database? 
I've found that due to combining these bytes,

```dart
class DjbECPublicKey extends ECPublicKey {
  final Uint8List _publicKey;

  DjbECPublicKey(this._publicKey);

  @override
  int getType() {
    return Curve.djbType;
  }

  @override
  Uint8List serialize() {
    return ByteUtil.combine([
      Uint8List.fromList([Curve.djbType]),
      _publicKey
    ]);
  }
```

you actually end up with 0x05 prepended to the Uint8List when `.serialize()` is called on the key (given that it's a `DjbECPublicKey`). This is causing the `InvalidKeyException` whenever `processPreKeyBundle()` is called.

**Comment by rlch** [comment]
My bad, @xni06 covered this in #21 - thanks mate!!

> As a quick pointer, you need to make use of a `DjbECPublicKey` to create a `ECPublicKey`:
> ```
> final key = DjbECPublicKey(yourUint8List);
> final ecPublicKey = Curve.decodePoint(key.serialize(), 1);
> ```

**Comment by Nitish987** [comment]
Thanks, I solved my code error from this.
