### ISSUE TITLE
Some implementation doubts

### ISSUE THREAD

**Issue by PaoloP98** [MixinNetwork/libsignal_protocol_dart#39]
From the example code, I see that this function generates a random number:
`var registerationId = KeyHelper.generateRegistrationId(false);`
Should I save this number in the database to retrieve it later? Must it be unique?
I saw that the deviceid on PreKeyBundle is an integer, in my database I save it as uuid. can I leave "1" as the value?

**Comment by crossle** [comment]
Yes, you save it to database or other persist location. and upload to server, wait other part request your signal keys.

**Comment by rlch** [comment]
@PaoloP98 I use `1` as I'm not planning on supporting accounts with multiple devices. If you are, then you should consider saving a [hash](https://pub.dev/packages/crypto) of the user's [device ID](https://pub.dev/packages/device_info_plus) for instance

**Comment by PaoloP98** [comment]
> Yes, you save it to database or other persist location. and upload to server, wait other part request your signal keys.

must have uniqueness as a constraint?

**Comment by crossle** [comment]
> must have uniqueness as a constraint?

Recommend unique

**Comment by PaoloP98** [comment]
> > must have uniqueness as a constraint?
> 
> Recommend unique

What if the random generation generates the same number? What should I do?

**Comment by rlch** [comment]
> > > must have uniqueness as a constraint?
> > 
> > 
> > Recommend unique
> 
> What if the random generation generates the same number? What should I do?

This is addressed by hashing the user's device ID, see my comment above

**Comment by PaoloP98** [comment]
> > > > must have uniqueness as a constraint?
> > > 
> > > 
> > > Recommend unique
> > 
> > 
> > What if the random generation generates the same number? What should I do?
> 
> This is addressed by hashing the user's device ID, see my comment above

I didn't understand why to hash the device id. Can you give me some clarification or a source?
Do you mean that even if the registerationId is not unique paired with the device id (unique) it is fine?
