### ISSUE TITLE
RangeError (index): Index out of range: no indices are valid: 0 

### ISSUE THREAD

**Issue by PrinceVergil** [MixinNetwork/libsignal_protocol_dart#45]
Hello,
I am getting Index out of range exception while encrypting message with bobGroupCipher in group session.

below is code i am using:
    
             
    void TestGroup() async {

    final senderAddress = SignalProtocolAddress('+00000000001', 1);
    final groupSender = SenderKeyName('Private group', senderAddress);

    final aliceStore = InMemorySenderKeyStore();
    final bobStore = InMemorySenderKeyStore();

    final aliceSessionBuilder = GroupSessionBuilder(aliceStore);
    final bobSessionBuilder = GroupSessionBuilder(bobStore);

    final aliceGroupCipher = GroupCipher(aliceStore, groupSender);
    final bobGroupCipher = GroupCipher(bobStore, groupSender);

    final sentAliceDistributionMessage =
        await aliceSessionBuilder.create(groupSender);
    final receivedAliceDistributionMessage =
        SenderKeyDistributionMessageWrapper.fromSerialized(
            sentAliceDistributionMessage.serialize());
    bobSessionBuilder.process(groupSender, receivedAliceDistributionMessage);

    var ciphertextFromAlice = await aliceGroupCipher
        .encrypt(Uint8List.fromList(utf8.encode('Hello Mixin')));
    var plaintextFromAlice = await bobGroupCipher.decrypt(ciphertextFromAlice);
    print("Alice msg to Bob : ${plaintextFromAlice}");

    ciphertextFromAlice = await bobGroupCipher
        .encrypt(Uint8List.fromList(utf8.encode('Hello Mixin')));
    plaintextFromAlice = await aliceGroupCipher.decrypt(ciphertextFromAlice);
    print("Bob msg to Alice  : ${plaintextFromAlice}");
    
       }

stacks trace 
` [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: RangeError (index): Index out of range: no indices are valid: 0
[        ] #0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2223:7)
[        ] #1      load3 (package:ed25519_edwards/src/edwards25519.dart:95:12)
[        ] #2      ScMulAdd (package:ed25519_edwards/src/edwards25519.dart:1273:22)
[        ] #3      sign (package:libsignal_protocol_dart/src/ecc/ed25519.dart:81:3)
[        ] #4      Curve.calculateSignature (package:libsignal_protocol_dart/src/ecc/curve.dart:125:14)
[        ] #5      SenderKeyMessage._getSignature (package:libsignal_protocol_dart/src/protocol/sender_key_message.dart:79:20)
[        ] #6      new SenderKeyMessage (package:libsignal_protocol_dart/src/protocol/sender_key_message.dart:27:9)
[        ] #7      GroupCipher.encrypt (package:libsignal_protocol_dart/src/groups/group_cipher.dart:29:32)
[        ] <asynchronous suspension>
[        ] #8      _TestingScreenState.TestGroup (package:chillflix/screens/testingScreen.dart:209:27)
[        ] <asynchronous suspension>`

**Comment by crossle** [comment]
Update the readme and example file https://github.com/MixinNetwork/libsignal_protocol_dart#building-a-group-session

**Comment by PrinceVergil** [comment]
Hiii  @crossle thanks for updating example but my problem is when I try to encrypt using bobGroupCipher  I get` Index out of range: no indices are`...  I am missing something. can you help with this.

**Comment by crossle** [comment]
You should use different sender and bobSessionBuilder.create sender key, then encrypt.

**Comment by PrinceVergil** [comment]
Correct me If I am wrong.. So you are saying every group member must share there DistributionMessage to each other.

**Comment by crossle** [comment]
Yes, share DistributionMessage each other on group

**Comment by mpweya** [comment]
Hello. Can you please post your now working example? I can't get it to work myself.

**Comment by mpweya** [comment]
@PrinceVergil have you solved your issue? Can you provide your working example. Or @crossle would you be so nice and write a quick example with multiple users like above?

**Comment by crossle** [comment]
Sorry for the delay, working on it.

**Comment by crossle** [comment]
> @PrinceVergil have you solved your issue? Can you provide your working example. Or @crossle would you be so nice and write a quick example with multiple users like above?

Who send the sender key message use it's sender key as param.

**Comment by mpweya** [comment]
> Who send the sender key message use it's sender key as param.

Thanks, was able to get it to work. This would be a working example (for anyone interested):
```dart
  final bobSenderAddress = SignalProtocolAddress('+00000000001', 1);
  final aliceSenderAddress = SignalProtocolAddress('+00000000002', 1);
  final bobGroupSender = SenderKeyName('Private group', bobSenderAddress);
  final aliceGroupSender = SenderKeyName('Private group', aliceSenderAddress);

  final aliceStore = InMemorySenderKeyStore();
  final bobStore = InMemorySenderKeyStore();

  final aliceSessionBuilder = GroupSessionBuilder(aliceStore);
  final bobSessionBuilder = GroupSessionBuilder(bobStore);

  final sentAliceDistributionMessage =
      await aliceSessionBuilder.create(aliceGroupSender);
  final receivedAliceDistributionMessage =
      SenderKeyDistributionMessageWrapper.fromSerialized(
          sentAliceDistributionMessage.serialize());
  bobSessionBuilder.process(aliceGroupSender, receivedAliceDistributionMessage);

  final sentBobDistributionMessage =
      await bobSessionBuilder.create(bobGroupSender);
  final receivedBobDistributionMessage =
      SenderKeyDistributionMessageWrapper.fromSerialized(
          sentBobDistributionMessage.serialize());
  aliceSessionBuilder.process(bobGroupSender, receivedBobDistributionMessage);

  var ciphertextFromAlice = await GroupCipher(aliceStore, aliceGroupSender)
      .encrypt(Uint8List.fromList(utf8.encode('Hello Mixin')));
  var plaintextFromAlice = await GroupCipher(bobStore, aliceGroupSender)
      .decrypt(ciphertextFromAlice);
  print("Alice msg to Bob : ${plaintextFromAlice}");

  ciphertextFromAlice = await GroupCipher(bobStore, bobGroupSender)
      .encrypt(Uint8List.fromList(utf8.encode('Hello Mixin')));
  plaintextFromAlice = await GroupCipher(aliceStore, bobGroupSender)
      .decrypt(ciphertextFromAlice);
  print("Bob msg to Alice  : ${plaintextFromAlice}");
```

**Comment by PrinceVergil** [comment]
@McCrafterIV  Thanks for the example I was busy in other stuff I look into it.
