### ISSUE TITLE
Production usage?

### ISSUE THREAD

**Issue by cremfert** [MixinNetwork/libsignal_protocol_dart#48]
Dear Mixin,

thanks a lot for providing such a great library - I'm thinking of using it in one of my production apps.
However, I have two questions regarding this:
- Do you consider this library already stable? Is it used somewhere in production?
- In your ratchet code (especially the ratchet session code) there is always hardcoded "Alice's session" and "Bob's session". Is this intended and real production code?

Thanks for your answer and effort!

**Comment by crossle** [comment]
1. Yes stable, we already use it in our desktop app [mixin messenger](https://mixin.one/mm)
2. Yes, we keep it naming like Java version libsignal

**Comment by cremfert** [comment]
Thanks a lot for your answer!
