### ISSUE TITLE
Use other cryptographic libraries?

### ISSUE THREAD

**Issue by cremfert** [MixinNetwork/libsignal_protocol_dart#49]
Dear Mixin,
would it be possible to use other libraries like libsodium or Dart's cryptography package for the ed25510 or x25519 algorithms? Why did you choose to create your own dart ports of the respective Go libraries?

Thanks a lot!

**Comment by crossle** [comment]
Some other dart library not export the some function for we usage. https://github.com/MixinNetwork/libsignal_protocol_dart/issues/40
