### ISSUE TITLE
IdentityKeyStore getIdentity returns nob-nullable IdentityKey

### ISSUE THREAD

**Issue by ffpetrovic** [MixinNetwork/libsignal_protocol_dart#50]
https://github.com/MixinNetwork/libsignal_protocol_dart/blob/master/lib/src/state/identity_key_store.dart#L14

Should it return `IdentityKey?` instead of `IdentityKey`? What if that identity with that address doesn't exist?

**Comment by crossle** [comment]
Yes, I think should be `IdentityKey?`

**Comment by crossle** [comment]
Fixed on 2662bebed5e77ab76db608552069bf0440ca611e

**Comment by ffpetrovic** [comment]
Thank you

**Comment by crossle** [comment]
Any PR welcome.
