### ISSUE TITLE
Deserialize IdentityKey

### ISSUE THREAD

**Issue by cremfert** [MixinNetwork/libsignal_protocol_dart#52]
I'm trying to deserialize an identity key that I stored in a file. For this, I used ```.serialize``` the key and then, to load it again, I use the ```IdentityKey.fromBytes``` method.

Here is a parameter required called ```offset```. Is this always ```0``` or does it have a different meaning?

Thanks a lot!

**Comment by Tougee** [comment]
Seems like a redundant parameter here, welcome PR to fix this.

**Comment by crossle** [comment]
The offset means if it's a DjbECPublicKey has a type on the prefix.
