### ISSUE TITLE
Assertion failed: Instance of 'InvalidKeyException' 

### ISSUE THREAD

**Issue by RahulAlchemy** [MixinNetwork/libsignal_protocol_dart#53]
In my project i was using this version `libsignal_protocol_dart: ^0.3.0-nullsafety.0`.
When i updated to this version `libsignal_protocol_dart: ^0.5.5`  i'm getting this error  `Assertion failed: Instance of 'InvalidKeyException' `
on encryption but other then that decryption works perfectly.

I'm getting this error on this line
`CiphertextMessage encryptedMessage =
        await cipher.encrypt(Uint8List.fromList(utf8.encode(data)));`

**Comment by crossle** [comment]
It's not logic change from the 0.3.0 to 0.5.

**Comment by pzehle** [comment]
@RahulAlchemy did you manage to solve this? I am getting the exact same error and I don't know how to solve it.

**Comment by RahulAlchemy** [comment]
> @RahulAlchemy did you manage to solve this? I am getting the exact same error and I don't know how to solve it.

@pzehle
Yes solved it.
Actually they change code for encryption and if you follow their release document you can  solved it too.

Old code


                       `  SessionBuilder.fromSignalStore(protocolStore, sender.address).processPreKeyBundle(bundle);
                          SessionCipher cipher = SessionCipher.fromStore(protocolStore, sender.address);
                         CiphertextMessage encryptedMessage = await cipher.encrypt(Uint8List.fromList(utf8.encode(data)));`

New code

                       `await sessionBuilder.processPreKeyBundle(bundle);
                        final sessionCipher = SessionCipher(sessionStore, preKeyStore,
                           signedPreKeyStore, identityStore, sender.address!);
                     final ciphertext =  await sessionCipher.encrypt(Uint8List.fromList(utf8.encode(data)));`

I hope this will help.

**Comment by pzehle** [comment]
@RahulAlchemy yes thank you, did this the trick.

Although I am a noob regarding the Signal Protocol, and to be honest this library is not well documented, now I am having trouble with the decryption. By any chance do you have a project I can take a look at? Or even documentation explaining the process?

Now I am getting:

`No such signedprekeyrecord! 0` Any ideas?

Thank you.

**Comment by crossle** [comment]
> @RahulAlchemy yes thank you, did this the trick.
> 
> Although I am a noob regarding the Signal Protocol, and to be honest this library is not well documented, now I am having trouble with the decryption. By any chance do you have a project I can take a look at? Or even documentation explaining the process?
> 
> Now I am getting:
> 
> `No such signedprekeyrecord! 0` Any ideas?
> 
> Thank you.

Follow this app https://github.com/mixinnetwork/flutter-app use this library.

**Comment by pzehle** [comment]
I've tried to. I don't really understand what they are doing, and also there are some functions that differ from the ones in the library. I guess I am doomed then.

Thank you anyway.
