### ISSUE TITLE
Is this interoperable with libsignal-protocol-java

### ISSUE THREAD

**Issue by XuanHanTan** [MixinNetwork/libsignal_protocol_dart#56]
I was wondering if the serialised keypairs from this package can be read in the Java version. Is this possible?

**Comment by Tougee** [comment]
I think it's possible because these serialized data are byte arrays.

**Comment by XuanHanTan** [comment]
Seems like libsignal-protocol-java can't parse the serialised keys from libsignal-protocol-dart. What a bummer!

**Comment by crossle** [comment]
> Seems like libsignal-protocol-java can't parse the serialised keys from libsignal-protocol-dart. What a bummer!

No, interoperable no problem libsignal-protocol-java with libsignal-protocol-dart. because we use both in our production.
You can send a demo or example on here.

**Comment by XuanHanTan** [comment]
By splitting the public/private keys, signature and id of the SignedPreKeyRecord instead of serialising the entire SignedPreKeyRecord, I could parse the keys in libsignal-protocol-java. On a side note, I am getting ArrayOutOfBounds errors on libsignal-protocol-java when generating a new signed prekey. It looks like it is related to protobuf. Do you have any experience with this?

**Comment by crossle** [comment]
Can you share some code on here, we use this library on https://github.com/mixinnetwork/flutter-app, work well with libsignal-protocol-java on Android

**Comment by XuanHanTan** [comment]
I actually managed to make it work by downgrading protobuf, thanks for your help! I will share some example code when I have time.
