### ISSUE TITLE
InvalidMessageException - No valid sessions. [InvalidMessageException - Bad Mac!][0]

### ISSUE THREAD

**Issue by magbdev** [MixinNetwork/libsignal_protocol_dart#58]
Sometimes I get this type of error while decrypting. Do you know why this exception occurs? And how handle it?

**Comment by crossle** [comment]
When the error occurs?

**Comment by magbdev** [comment]
A session between two users is already set up and messages are exchanged, and at some point this error occurs. It seems to be a random moment.

**Comment by crossle** [comment]
Try the test function. https://github.com/MixinNetwork/libsignal_protocol_dart/blob/master/test/session_cipher_test.dart#L170

**Comment by ronpetit** [comment]
I'm receiving the same error message, in my case, it happens when i try to establish a new session with the mobile phone as the first recipient (I'm having a mobile client and a web client)

Somehow, it is just working when the APP the is the one to establish the session at first

**Comment by ronpetit** [comment]
Actually, my problem is because the mobile starts a session and then the webapp doesn't answer inmediately, so after the webapp answer the mobile APP can be closed and when is restored it doesn't have the established session alive to be able to decrypt the message

**Comment by WiRight** [comment]
same here

any updates with this issue?

**Comment by Tougee** [comment]
Have the identities of the established session changed?

**Comment by Nitish987** [comment]
I got the same error 
`InvalidMessageException - No valid sessions. [InvalidMessageException - Bad Mac!, InvalidMessageException - Bad Mac!, InvalidMessageException - Bad Mac!, InvalidMessageException - Bad Mac!, InvalidMessageException - Bad Mac!, InvalidMessageException - Bad Mac!, InvalidMessageException - Bad Mac!][0]`

First time installing the app it works fine and second time when I reopens the app the  message got encrypted but not decrypted and giving this above error.

**Comment by anisalibegic** [comment]
> Have the identities of the established session changed?

What to do if they are?

**Comment by Nitish987** [comment]
Again create the session if the identity keys are changed.

**Comment by anisalibegic** [comment]
> Again create the session if the identity keys are changed.

How do you determine if identity keys are changed? Is it enough to use `signalProtocolStore.isTrustedIdentity` method? In other words if identity is trusted skip establishing session.

**Comment by Nitish987** [comment]
yes you can use this function too

**Comment by loscoy** [comment]
Same error, did you fixed it?
