### ISSUE TITLE
whisperType CiphertextMessage

### ISSUE THREAD

**Issue by abhay-s-rawat** [MixinNetwork/libsignal_protocol_dart#61]
I am but confused with the following types of CiphertextMessage.

When we will get whisperType type message ? I guess it will be message when reciever bundle had no 1 time key present , right ? In that case when creating PreKeyBundle the int _preKeyId, ECPublicKey _preKeyPublic should be nullable , right ? as stated in https://signal.org/docs/specifications/x3dh/

```
If the bundle does not contain a one-time prekey, she calculates:

    DH1 = DH(IKA, SPKB)
    DH2 = DH(EKA, IKB)
    DH3 = DH(EKA, SPKB)
    SK = KDF(DH1 || DH2 || DH3)

If the bundle does contain a one-time prekey, the calculation is modified to include an additional DH:

    DH4 = DH(EKA, OPKB)
    SK = KDF(DH1 || DH2 || DH3 || DH4)
```

```
  static const int whisperType = 2; //=> When we will get this ?
  static const int prekeyType = 3; //  When sender had one time pre key of receiver
  static const int senderKeyType = 4; // group msg type, I guess
  static const int senderKeyDistributionType = 5; // This is initial kdm msg , used in groups
```

bundle implementation as below
```
PreKeyBundle getPreKeyBundle(Map<String, dynamic> remoteBundle) {
    ECPublicKey tempPrePublicKey = Curve.decodePoint(
        DjbECPublicKey(base64Decode(remoteBundle["preKeys"].first['key']))
            .serialize(),
        1);
    int tempPreKeyId = remoteBundle["preKeys"].first['id'];
    int tempSignedPreKeyId = remoteBundle["signedPreKey"]['id'];
    ECPublicKey? tempSignedPreKeyPublic = Curve.decodePoint(
        DjbECPublicKey(base64Decode(remoteBundle["signedPreKey"]['key']))
            .serialize(),
        1);
    Uint8List? tempSignedPreKeySignature =
        base64Decode(remoteBundle["signedPreKey"]['signature']);
    IdentityKey tempIdentityKey = IdentityKey(Curve.decodePoint(
        DjbECPublicKey(base64Decode(remoteBundle["identityKey"])).serialize(),
        1));
    return PreKeyBundle(
      remoteBundle['registrationId'],
      1,
      tempPreKeyId,
      tempPrePublicKey,
      tempSignedPreKeyId,
      tempSignedPreKeyPublic,
      tempSignedPreKeySignature,
      tempIdentityKey,
    );
  }
```

**Comment by abhay-s-rawat** [comment]
I will do a pull request as soon I as I am finished with my example to make example more informative. Group part is remaining.

**Comment by abhay-s-rawat** [comment]
Seems like its already implemented but not pushed to pub.dev.

can you please answer When we will get whisperType type message ?

**Comment by Tougee** [comment]
Yes, nullable `one-time prekey` is implemented in https://github.com/MixinNetwork/libsignal_protocol_dart/commit/7a486a57efc1bc7026b8c7f5fd4cbe08d49d1b56 but are not yet published.

The `whisperType` is related to `SignalMessage`, and as part of the Double Ratchet Protocol, you will receive this type of message when users are texting each other.

**Comment by crossle** [comment]
Published https://pub.dev/packages/libsignal_protocol_dart

**Comment by abhay-s-rawat** [comment]
> Yes, nullable `one-time prekey` is implemented in [7a486a5](https://github.com/MixinNetwork/libsignal_protocol_dart/commit/7a486a57efc1bc7026b8c7f5fd4cbe08d49d1b56) but are not yet published.
> 
> The `whisperType` is related to `SignalMessage`, and as part of the Double Ratchet Protocol, you will receive this type of message when users are texting each other.

But I am always getting prekeyType message . What to do ?

```
PreKeySignalMessage pre = PreKeySignalMessage(base64Decode(data["msg"]));
```

**Comment by Tougee** [comment]
whisperType messages are generated by encrypt in session_cipher.dart, and examples in session_cipher_test.dart

**Comment by abhay-s-rawat** [comment]
Sorry for the confusion. When session is established from both ends I am getting whispertype messages. I am working on a example to demonstrate things clearly.
Well in latest PreKeyBundle we can establish session without one time pre keys, that ok but why are signedpre keys nullable ? Am I missing something ?
```
(new) PreKeyBundle PreKeyBundle(
  int _registrationId,
  int _deviceId,
  int? _preKeyId,
  ECPublicKey? _preKeyPublic,
  int _signedPreKeyId,
  ECPublicKey? _signedPreKeyPublic,
  Uint8List? _signedPreKeySignature,
  IdentityKey _identityKey,
)
```

**Comment by abhay-s-rawat** [comment]
I am currently decrypting like below, is there a class that is parent of both PreKeySignalMessage ,SignalMessage ?
Because I have to send message type in payload seperatly to deal with msg types.
```
Map data = jsonDecode(msg);
    if (data["type"] == CiphertextMessage.prekeyType) {
      PreKeySignalMessage pre = PreKeySignalMessage(base64Decode(data["msg"]));
      Uint8List plaintext = await session.decrypt(pre);
      String dectext = utf8.decode(plaintext);
      return dectext;
    } else if (data["type"] == CiphertextMessage.whisperType) {
      SignalMessage signalMsg =
          SignalMessage.fromSerialized(base64Decode(data["msg"]));
      Uint8List plaintext = await session.decryptFromSignal(signalMsg);
      String dectext = utf8.decode(plaintext);
      return dectext;
    } else {
      return "signal msg";
    }
```

**Comment by Tougee** [comment]
> Well in latest PreKeyBundle we can establish session without one time pre keys, that ok but why are signedpre keys nullable ? Am I missing something ?

I don't think this is necessary, but it will help this library have better interoperability with other libraries implemented by other languages, like Java. If we receive a nullable signed prekey from the Java side, then we can successfully deserialize and throw the right exception to the caller.

> is there a class that is parent of both PreKeySignalMessage ,SignalMessage ?

CiphertextMessage?

**Comment by abhay-s-rawat** [comment]
CiphertextMessage is abstract.

Currently I am using a map which is jsonencoded as a payload to send , in that payload I was sending the type of message and while decrypting I was checking that type and decrypt accordingly.

I made example project look like below as soon as I finish for group , I will give pull request.
![Screenshot_1665327481](https://user-images.githubusercontent.com/84996356/194763951-a09012f6-0844-41b8-8e87-45b4f3cf4c4e.png)

**Comment by Tougee** [comment]
This is great! Expect your PR.

**Comment by abhay-s-rawat** [comment]
https://github.com/MixinNetwork/libsignal_protocol_dart/pull/62
Did pr.

**Comment by abhay-s-rawat** [comment]
I was also thinking to show how to change signedprekeys but I fell short of vision. Did you remember "your security code has been changed with $user" from whatsapp, is it because of signed prekeys  or user changed phone and identity keys got reset .

How changing signed prekey will hurt existing sessions, can you help me out in this ? I have to update example for this.
Already gave fingerprint comparision aka safety number in terms of signal protocol in example.

**Comment by Tougee** [comment]
👍 Thanks for the great work, I'll review it asap.

> Did you remember "your security code has been changed with $user" from whatsapp, is it because of signed prekeys or user changed phone and identity keys got reset .

AFAIK yes.

> How changing signed prekey will hurt existing sessions

A new session should be established via the X3DH protocol if one side clear/reset keys.

**Comment by abhay-s-rawat** [comment]
1 more thing to ask.
Some of the classes below throw errors when something is not present, can it return null if key not present instead of throwing error ?
like Future<PreKeyRecord> loadPreKey will become Future<PreKeyRecord?> loadPreKey.

```
import 'dart:collection';
import 'dart:typed_data';

import '../../invalid_key_id_exception.dart';
import '../pre_key_record.dart';
import '../pre_key_store.dart';

class InMemoryPreKeyStore extends PreKeyStore {
  final store = HashMap<int, Uint8List>();

  @override
  Future<bool> containsPreKey(int preKeyId) async =>
      store.containsKey(preKeyId);

  @override
  Future<PreKeyRecord> loadPreKey(int preKeyId) async {
    if (!store.containsKey(preKeyId)) {
      throw InvalidKeyIdException('No such prekeyrecord! - $preKeyId');
    }
    return PreKeyRecord.fromBuffer(store[preKeyId]!);
  }

  @override
  Future<void> removePreKey(int preKeyId) async {
    store.remove(preKeyId);
  }

  @override
  Future<void> storePreKey(int preKeyId, PreKeyRecord record) async {
    store[preKeyId] = record.serialize();
  }
}

```

**Comment by Tougee** [comment]
No special reasons, we ported this library from Java and adopted this style.

**Comment by abhay-s-rawat** [comment]
Actually I am thinking to make it more like dart implementation. Is it ok to do so ?

**Comment by crossle** [comment]
> Actually I am thinking to make it more like dart implementation. Is it ok to do so ?

This only for InMemoryPreKeyStore, You can implements your self PreKeyStore.

**Comment by abhay-s-rawat** [comment]
> > Actually I am thinking to make it more like dart implementation. Is it ok to do so ?
> 
> This only for InMemoryPreKeyStore, You can implements your self PreKeyStore.

Yes I implemented self store but the thing is the abstract class has "Future of PreKeyRecord loadPreKey" definition due to which all extented class must return non nullable objects.

**Comment by abhay-s-rawat** [comment]
My self store published below, if you plan to change types to nullable rather than throwing errors , please do tell me by opening a issue in (https://github.com/abhay-s-rawat/libsignal_protocol_hive_store).
Thanks for your time.
https://pub.dev/packages/libsignal_protocol_hive_store

**Comment by crossle** [comment]
> > > Actually I am thinking to make it more like dart implementation. Is it ok to do so ?
> > 
> > 
> > This only for InMemoryPreKeyStore, You can implements your self PreKeyStore.
> 
> Yes I implemented self store but the thing is the abstract class has "Future of PreKeyRecord loadPreKey" definition due to which all extented class must return non nullable objects.

Cool, Welcome PR
