### ISSUE TITLE
PreKeyBundle to Server

### ISSUE THREAD

**Issue by Nitish987** [MixinNetwork/libsignal_protocol_dart#69]
Can anyone tell about how can i send PreKeyBundle to server. 
I have implemented with some approach but theres a problem in converting Uint8List PreKey to ECPublicKey Class Object on getting PreKeyBundleModel back from the server. 

I have created this PreKeyBundleModel which is coming from server after deserializing but i have to convert this PreKeyBundleModel to PreKeyBundle. Problem occurs when i want to convert Uinit8List PreKey to ECPublicKey as PreKeyBundle  requires ECPublicKey Object as parameters. Is there any method to convert Uini8List to ECPublicKey.

`
@JsonSerializable()
class PreKeyBundleModel {
  int? registrationId;
  int? deviceId;
  List<PreKeyModel>? preKeys;
  SignedPreKeyModel? signedPreKey;
  String? identityKey;

  PreKeyBundleModel({this.registrationId, this.deviceId, this.preKeys, this.signedPreKey, this.identityKey});

  factory PreKeyBundleModel.fromJson(Map<String, dynamic> json) => _$PreKeyBundleModelFromJson(json);

  Map<String, dynamic> toJson() => _$PreKeyBundleModelToJson(this);
}

@JsonSerializable()
class PreKeyModel {
  int? id;
  String? key;

  PreKeyModel({this.id, this.key});

  factory PreKeyModel.fromJson(Map<String, dynamic> json) => _$PreKeyModelFromJson(json);

  Map<String, dynamic> toJson() => _$PreKeyModelToJson(this);
}

@JsonSerializable()
class SignedPreKeyModel {
  int? id;
  String? key;
  String? signature;

  SignedPreKeyModel({this.id, this.key, this.signature});

  factory SignedPreKeyModel.fromJson(Map<String, dynamic> json) => _$SignedPreKeyModelFromJson(json);

  Map<String, dynamic> toJson() => _$SignedPreKeyModelToJson(this);
}
`

**Comment by Tougee** [comment]
You can try `DjbECPublicKey` which has a constructor that accepts `Uint8List` as a parameter.

**Comment by Nitish987** [comment]
I have tried using DjbECPublicKey but gives an error

`InvalidKeyException - Invalid signature on device key!`

prekeybundle

`PreKeyBundle(
     bob_registration_id,
     bob_deviceId,
     bob_prekey_id,
     DjbECPublicKey(bob_prekey),
     signed_prekey_id,
     DjbECPublicKey(signed_prekey),
     signed_prekey_.signature,
     IdentityKey(DjbECPublicKey(identity_public_key)),
),
`

**Comment by Nitish987** [comment]
Thank you so much i solved my code error.
