### ISSUE TITLE
InMemorySessionStore

### ISSUE THREAD

**Issue by peter100u** [MixinNetwork/libsignal_protocol_dart#7]
InMemorySessionStore 看了很多资料都是内存保存这个store， 开发中是不是要放到数据库中InDbSessionStore，网上对于signal  的资料太少了，也没有 demo看，有好的建议吗，一个开发im 老鸟

**Comment by ghost** [comment]
>InMemorySessionStore I saw that a lot of information is stored in the memory. Is it necessary to put it in the database InDbSessionStore during development? There is too little information about signal on the Internet, and there is no demo. Do you have any good suggestions? A development im veteran

We have implemented all store interfaces using [get_storage](https://pub.dev/packages/get_storage) for our demo app - we might be able to make it available to the public at some point.

**Comment by Tougee** [comment]
Hi, @superLiuYiPeng.
Depending on your use case, most of the time you should use a database based SessionStore like SignalApp or MixinMessenger dose.

https://github.com/MixinNetwork/android-app/tree/master/app/src/main/java/one/mixin/android/crypto/storage
