### ISSUE TITLE
InvalidMessageException

### ISSUE THREAD

**Issue by Nitish987** [MixinNetwork/libsignal_protocol_dart#70]
I got the error

`InvalidMessageException - No valid sessions. [InvalidMessageException - Bad Mac!, InvalidMessageException - Bad Mac!, InvalidMessageException - Bad Mac!, InvalidMessageException - Bad Mac!, InvalidMessageException - Bad Mac!, InvalidMessageException - Bad Mac!, InvalidMessageException - Bad Mac!][0]`

First time installing the app it works fine and second time when I reopens the app the message got encrypted but not decrypted and giving this above error.

**Comment by simonasposka** [comment]
Hey @Nitish987, did you manage to solve this problem?

I sometimes get this error in my application, but I can't reproduce it 🤔
