### ISSUE TITLE
How to handle generateRegistrationId collision?

### ISSUE THREAD

**Issue by Turbozanik** [MixinNetwork/libsignal_protocol_dart#77]
Hi all. I am working on an app featuring this library.

And I was not able to find any scenarious neither in Signal protocol description, neither here for a generateRegistrationId numbers collision.
I am not even sure do we care about it or not?

Les's take a look a the following scenario:
Alice id = 1
Bob's id = 1

When Bob sends his ID to the server, and there is already Alice with the same id, what should we do?

My guess would be, send Bob an error that should generate all the ids/keys from scratch and make another server call.

Can you help me with that?

**Comment by Tougee** [comment]
Hi, afaik there is no effect if different users with the same `registrationId`.
