### ISSUE TITLE
Release new version with updated dependencies

### ISSUE THREAD

**Issue by mpweya** [MixinNetwork/libsignal_protocol_dart#84]
The protobuf package has released a new major version (4.0.0) which this packages has been updated to in the pubspec.yaml in commit https://github.com/MixinNetwork/libsignal_protocol_dart/commit/1b4e35906f79aab5e9a71246d073032926ef6a0c . But since then, beginning of june 2024, there was no update pushed to pub.dev, leaving the released 0.7.1 incompatible with protobuf 4.0.0.

Can you release a new version on pub.dev so that the package is compatible with other packages using protobuf 4.0.0?

**Comment by crossle** [comment]
Where is the protobuf 4.0.0 version?

**Comment by mpweya** [comment]
Sorry my Bad, I was talking about 3.0.0

**Comment by crossle** [comment]
Published new version.

**Comment by mpweya** [comment]
Thanks for the quick update!
